name: "Build docker image"
description: "Builds a Docker image and publishes it to ECR"
inputs:
  registry:
    description: "Registry name"
    required: true
  repository:
    description: "Repository name"
    required: true
  image-tag:
    description: "tag name"
    required: true
  build-path:
    description: "path to dockerfile"
    default: "./"
    required: false
  build-args:
    description: "build args"
    default: ""
    required: false
runs:
  using: "composite"
  steps:
    - name: Publish docker image
      shell: bash
      env:
        REGISTRY: ${{ inputs.registry }}
        REPOSITORY: ${{ inputs.repository }}
        IMAGE_TAG: ${{ inputs.image-tag }}
        BUILD_PATH: ${{ inputs.build-path }}
        BUILD_ARGS: ${{ inputs.build-args }}
      run: $GITHUB_ACTION_PATH/build-image.sh
