name: Publish service
on:
  push:
    tags:
      - "*"

permissions:
      id-token: write
      contents: write    # This is required for actions/checkout@v1
jobs:
  image-tag:
    name: image-tag
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.clean-ref.outputs.tag }}
    steps:
      - name: Clean git ref
        id: clean-ref
        run: |
          TAG=${GITHUB_REF##*/}
          echo "tag=${TAG}" >> $GITHUB_OUTPUT
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [image-tag]
    steps:
      - uses: actions/checkout@v2
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::077212880246:role/k8s-github-action-redash
          role-duration-seconds: 3600
      - name: Build image
        id: docker-build
        uses: ./.github/actions/build-image
        with:
          registry: "077212880246.dkr.ecr.us-east-1.amazonaws.com"
          repository: "systems/redash"
          image-tag: ${{ needs.image-tag.outputs.tag }}



